version: '3.8'

services:
  frontend:
    container_name: frontend
    build: ./Sambhav-React-App
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend

