name: Deploy to Self-Hosted Runner

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env: 
          SONAR_TOKEN: ${{ secrest.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        
        
      
      - name: Build Docker containers
        run: |
          # Navigate to the application directory
          cd /home/sambhav/Downloads/superset-master

          # Build the Docker containers from the Dockerfile(s)
          docker-compose -f docker-compose.yml build
          
          docker-compose -f docker-compose.yml down
          
          docker-compose -f docker-compose.yml up -d

         
