name: Deploy to EC2

on:
  push:
    branches:
      - master  # Updated to use master branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_PORT: ${{ secrets.EC2_PORT }}
      EC2_USER: ${{ secrets.EC2_USER }}
      DEPLOY_DIR: '/home/ubuntu/supersettt'  # Path to your project with docker-compose.yml

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy latest code with zero downtime
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ env.EC2_PORT }} ${{ env.EC2_USER }}@${{ env.EC2_HOST }} << EOF
          cd ${DEPLOY_DIR}
          git pull origin master               # Pull latest changes from the master branch
          docker-compose up -d --build         # Rebuild and recreate services without downtime
        EOF

    - name: Notify success
      if: success()
      run: echo "Deployment successful!"

    - name: Notify failure
      if: failure()
      run: echo "Deployment failed."
